server:
  port: 8109

#spring:
#  jpa:
#    show-sql: true
#
#
#    hibernate:
#      ddl-auto: update
#    database: h2
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url:jdbc:h2: ~/test
spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:userdb
  h2:
    console:
      enabled: true
  application:
    name: mcmaster-admin

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true