server:
  port: 9091

spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:bookstoredb
  mvc:
    format:
      date: yyyy-MM-dd
  h2:
    console:
      enabled: true
  application:
    name: bookstore-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true