server:
  port: 9091

spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:bookstoredb
  mvc:
    format:
      date: yyyy-MM-dd
  h2:
    console:
      enabled: true

