server:
  port: 9290

spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:trackingdb
  h2:
    console:
      enabled: true
  application:
    name: tracker-service
    cloud:
      inetutils:
        preferredNetworks:
          - 192.168
          - 10.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
